// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6D-IjKT_fZpEYdMsrSweLPyhnKUpuE4',
    appId: '1:73687948008:web:208b953c53d20577b3c75d',
    messagingSenderId: '73687948008',
    projectId: 'status-hub-bd177',
    authDomain: 'status-hub-bd177.firebaseapp.com',
    storageBucket: 'status-hub-bd177.firebasestorage.app',
    measurementId: 'G-WYEDVP8K9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzawOI6U1DJIGQSgtd088Hgl4oGHWAoug',
    appId: '1:73687948008:android:32ecd481da2f524bb3c75d',
    messagingSenderId: '73687948008',
    projectId: 'status-hub-bd177',
    storageBucket: 'status-hub-bd177.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JM2QpJtiv92cMDVjmuVHrEcg8UIv6Kk',
    appId: '1:73687948008:ios:9e7aba5520b1b780b3c75d',
    messagingSenderId: '73687948008',
    projectId: 'status-hub-bd177',
    storageBucket: 'status-hub-bd177.firebasestorage.app',
    iosBundleId: 'com.appsbyanandakumar.statushub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_JM2QpJtiv92cMDVjmuVHrEcg8UIv6Kk',
    appId: '1:73687948008:ios:9e7aba5520b1b780b3c75d',
    messagingSenderId: '73687948008',
    projectId: 'status-hub-bd177',
    storageBucket: 'status-hub-bd177.firebasestorage.app',
    iosBundleId: 'com.appsbyanandakumar.statushub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB6D-IjKT_fZpEYdMsrSweLPyhnKUpuE4',
    appId: '1:73687948008:web:d71ffb57949714dfb3c75d',
    messagingSenderId: '73687948008',
    projectId: 'status-hub-bd177',
    authDomain: 'status-hub-bd177.firebaseapp.com',
    storageBucket: 'status-hub-bd177.firebasestorage.app',
    measurementId: 'G-DWLC4EJ07V',
  );
}
